//! Codex Terms-of-Service acknowledgement marker.
//!
//! Spec 07 §7.3.3 step 3 pre-seeds `config-<N>/config.toml` with the
//! file-backed auth store. Before that happens in the desktop Add
//! Account flow, the user MUST be shown a disclosure explaining that
//! authenticating a Codex account consumes ChatGPT-subscription quota
//! from their OpenAI account. The disclosure is explicit, not a
//! passive scroll — we record acknowledgement by writing
//! `accounts/codex-tos-accepted.json` once. Absence of the marker
//! means the UI MUST show the disclosure and gate the proceed button
//! on the acknowledgement call.
//!
//! The marker is write-once, 0o600, atomic-rename. The absence state
//! is authoritative — a user who wants to revoke acknowledgement can
//! delete the file, and the next Add Account Codex flow will require
//! a fresh acknowledgement.
//!
//! This module is surface-scoped (`providers/codex/`) because the
//! disclosure text is Codex-specific (references ChatGPT subscription
//! terms + cross-surface session non-transfer). A future Gemini
//! surface would have its own sibling marker under
//! `providers/gemini/tos.rs`.

use crate::platform::fs::{atomic_replace, secure_file, unique_tmp_path};
use serde::{Deserialize, Serialize};
use std::io;
use std::path::{Path, PathBuf};

/// Filename relative to `base_dir` (`~/.claude/accounts/`). A single
/// account-scope marker — one per machine — since ToS acknowledgement
/// is a human decision, not a per-slot state.
pub const TOS_MARKER_FILENAME: &str = "codex-tos-accepted.json";

/// Payload stamped into the marker file. Kept minimal on purpose —
/// the marker is a boolean presence test; the timestamp is diagnostic
/// only.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TosMarker {
    /// ISO-8601 UTC timestamp of the acknowledgement (e.g.
    /// `"2026-04-23T12:34:56Z"`). Generated by [`acknowledge`].
    pub acknowledged_at: String,
    /// Fixed at `1` today. Future revisions of the disclosure bump
    /// this; the UI gates on version equality rather than mere
    /// presence so users re-acknowledge when terms change.
    pub version: u32,
}

/// Current ToS version. Increment and re-ship to force every user
/// through the disclosure again.
pub const CURRENT_TOS_VERSION: u32 = 1;

/// Returns the absolute path to the ToS marker file.
pub fn tos_marker_path(base_dir: &Path) -> PathBuf {
    base_dir.join(TOS_MARKER_FILENAME)
}

/// Returns `true` when the user has acknowledged the current Codex
/// ToS version. Absence, wrong version, or a malformed marker all
/// return `false` — the UI re-prompts in every case.
pub fn is_acknowledged(base_dir: &Path) -> bool {
    let path = tos_marker_path(base_dir);
    let Ok(raw) = std::fs::read_to_string(&path) else {
        return false;
    };
    let Ok(parsed) = serde_json::from_str::<TosMarker>(&raw) else {
        return false;
    };
    parsed.version == CURRENT_TOS_VERSION
}

/// Atomically writes the ToS marker at the current version with an
/// ISO-8601 timestamp derived from `SystemTime::now`. Idempotent —
/// calling twice leaves the marker at the most recent timestamp,
/// which is acceptable because the only semantic the caller reads
/// back is version equality.
pub fn acknowledge(base_dir: &Path) -> io::Result<TosMarker> {
    acknowledge_at(base_dir, current_timestamp())
}

/// Internal helper for tests that want to pin the timestamp.
pub(crate) fn acknowledge_at(base_dir: &Path, acknowledged_at: String) -> io::Result<TosMarker> {
    if !base_dir.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("base dir does not exist: {}", base_dir.display()),
        ));
    }

    let marker = TosMarker {
        acknowledged_at,
        version: CURRENT_TOS_VERSION,
    };
    let json =
        serde_json::to_string_pretty(&marker).map_err(|e| io::Error::other(e.to_string()))?;

    let target = tos_marker_path(base_dir);
    let tmp = unique_tmp_path(&target);

    if let Err(e) = std::fs::write(&tmp, json.as_bytes()) {
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    if let Err(e) = secure_file(&tmp) {
        let _ = std::fs::remove_file(&tmp);
        return Err(io::Error::other(e.to_string()));
    }
    if let Err(e) = atomic_replace(&tmp, &target) {
        let _ = std::fs::remove_file(&tmp);
        return Err(io::Error::other(e.to_string()));
    }

    Ok(marker)
}

fn current_timestamp() -> String {
    // Minimal ISO-8601 UTC formatter — avoids pulling `chrono` just for
    // a human-readable marker. Format: `YYYY-MM-DDTHH:MM:SSZ`.
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    // Delegate to the one chrono-free formatter already in the
    // codebase (if any). Fall back to epoch-seconds wrapping.
    format_utc_seconds(now)
}

fn format_utc_seconds(secs: u64) -> String {
    // days_from_civil algorithm — Howard Hinnant's canonical.
    let days = (secs / 86_400) as i64;
    let sod = secs % 86_400;
    let (y, m, d) = civil_from_days(days);
    let hh = sod / 3600;
    let mm = (sod / 60) % 60;
    let ss = sod % 60;
    format!("{y:04}-{m:02}-{d:02}T{hh:02}:{mm:02}:{ss:02}Z")
}

fn civil_from_days(z: i64) -> (i32, u32, u32) {
    let z = z + 719_468;
    let era = (if z >= 0 { z } else { z - 146_096 }) / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    let y = if m <= 2 { y + 1 } else { y };
    (y as i32, m, d)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn is_acknowledged_returns_false_when_marker_missing() {
        let dir = TempDir::new().unwrap();
        assert!(!is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_then_is_acknowledged_returns_true() {
        let dir = TempDir::new().unwrap();
        acknowledge(dir.path()).unwrap();
        assert!(is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_writes_iso8601_timestamp_and_current_version() {
        let dir = TempDir::new().unwrap();
        let m = acknowledge_at(dir.path(), "2026-04-23T12:34:56Z".into()).unwrap();
        assert_eq!(m.version, CURRENT_TOS_VERSION);
        assert_eq!(m.acknowledged_at, "2026-04-23T12:34:56Z");

        let raw = std::fs::read_to_string(tos_marker_path(dir.path())).unwrap();
        assert!(raw.contains("\"version\": 1"));
        assert!(raw.contains("2026-04-23T12:34:56Z"));
    }

    #[test]
    fn acknowledge_is_idempotent() {
        let dir = TempDir::new().unwrap();
        acknowledge_at(dir.path(), "2026-04-23T00:00:00Z".into()).unwrap();
        acknowledge_at(dir.path(), "2026-04-23T00:00:01Z".into()).unwrap();
        // Second write wins at the timestamp level — version still valid.
        assert!(is_acknowledged(dir.path()));
        let raw = std::fs::read_to_string(tos_marker_path(dir.path())).unwrap();
        assert!(raw.contains("2026-04-23T00:00:01Z"));
    }

    #[test]
    fn wrong_version_is_not_acknowledged() {
        let dir = TempDir::new().unwrap();
        let path = tos_marker_path(dir.path());
        std::fs::write(
            &path,
            r#"{"acknowledged_at":"2026-01-01T00:00:00Z","version":99}"#,
        )
        .unwrap();
        assert!(
            !is_acknowledged(dir.path()),
            "a newer version in the file means the user has not seen the CURRENT disclosure"
        );
    }

    #[test]
    fn malformed_marker_is_not_acknowledged() {
        let dir = TempDir::new().unwrap();
        let path = tos_marker_path(dir.path());
        std::fs::write(&path, "not json").unwrap();
        assert!(!is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_rejects_nonexistent_base_dir() {
        let dir = TempDir::new().unwrap();
        let missing = dir.path().join("does-not-exist");
        let err = acknowledge(&missing).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::NotFound);
    }

    #[cfg(unix)]
    #[test]
    fn marker_file_is_mode_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        acknowledge(dir.path()).unwrap();
        let mode = std::fs::metadata(tos_marker_path(dir.path()))
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600, "ToS marker must be 0o600");
    }

    #[test]
    fn format_utc_seconds_round_numbers() {
        assert_eq!(format_utc_seconds(0), "1970-01-01T00:00:00Z");
        assert_eq!(format_utc_seconds(86_400), "1970-01-02T00:00:00Z");
        assert_eq!(format_utc_seconds(1_775_722_800), "2026-04-09T08:20:00Z");
    }
}
