//! Gemini Terms-of-Service acknowledgement marker.
//!
//! csq spawns the official `gemini` CLI as a subprocess; gemini-cli
//! handles its own auth (Code Assist OAuth, AI Studio API key, or
//! Vertex SA). This file is the marker for a one-time INFORMATIONAL
//! disclosure shown in the desktop AddAccount flow on first Gemini
//! provisioning — explaining how csq wraps gemini-cli, what state
//! csq writes to the slot's `.gemini/settings.json`, and how to
//! switch auth modes. Earlier revisions framed this as a ToS-driven
//! defense ("Google ToS prohibits routing subscription OAuth through
//! third-party tools") — that framing was wrong and has been
//! retracted (an internal journal entry). The marker stays because the
//! informational walkthrough is still useful first-time content; the
//! disclosure copy itself is now neutral.
//!
//! The marker is write-once, 0o600, atomic-rename — same pipeline as
//! every other credential write per `rules/security.md` §4 + §5a. The
//! absence state is authoritative: a user who wants to revoke
//! acknowledgement can delete the file, and the next Add Account flow
//! will require a fresh acknowledgement.
//!
//! Surface-scoped because the disclosure text is Gemini-specific (the
//! gemini-cli wrap walkthrough is distinct from the Codex device-auth
//! walkthrough in tone and content). Sibling pattern of
//! `providers/codex/tos.rs`.

use crate::platform::fs::{atomic_replace, secure_file, unique_tmp_path};
use serde::{Deserialize, Serialize};
use std::io;
use std::path::{Path, PathBuf};

/// Filename relative to `base_dir` (`~/.claude/accounts/`). One marker
/// per machine — ToS acknowledgement is a human decision, not a
/// per-slot state.
pub const TOS_MARKER_FILENAME: &str = "gemini-tos-accepted.json";

/// Payload stamped into the marker. Minimal on purpose — the marker
/// is a boolean presence test; the timestamp is diagnostic only.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TosMarker {
    /// ISO-8601 UTC timestamp of the acknowledgement (e.g.
    /// `"2026-04-26T12:34:56Z"`). Generated by [`acknowledge`].
    pub acknowledged_at: String,
    /// Fixed at `1` today. Future revisions of the disclosure bump
    /// this; the UI gates on version equality so users re-acknowledge
    /// when terms change.
    pub version: u32,
}

/// Current disclosure version. Increment to force every user through
/// the disclosure again.
///
/// **v2 (2026-05-06, an internal journal entry):** the disclosure copy was rewritten
/// from a ToS-warning framing ("Google ToS prohibits OAuth subscription
/// rerouting through third-party tools — csq actively defends against
/// this with a 7-layer guard") to an informational walkthrough
/// ("csq spawns the official gemini CLI as a subprocess; auth uses
/// whatever gemini-cli is configured for"). Users who acknowledged v1
/// (the old alarmist text) MUST re-acknowledge so they see the
/// corrected description of what csq actually does.
pub const CURRENT_TOS_VERSION: u32 = 2;

/// Returns the absolute path to the ToS marker file.
pub fn tos_marker_path(base_dir: &Path) -> PathBuf {
    base_dir.join(TOS_MARKER_FILENAME)
}

/// Returns `true` when the user has acknowledged the current Gemini
/// ToS version. Absence, wrong version, or a malformed marker all
/// return `false` — the UI re-prompts in every case. Mirrors
/// `codex::tos::is_acknowledged` failure-mode logging discipline.
pub fn is_acknowledged(base_dir: &Path) -> bool {
    let path = tos_marker_path(base_dir);
    let raw = match std::fs::read_to_string(&path) {
        Ok(r) => r,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return false,
        Err(e) => {
            tracing::warn!(
                path = %path.display(),
                error_kind = "gemini_tos_marker_read_failed",
                error = %e,
                "cannot read Gemini ToS marker — treating as not acknowledged \
                 (check filesystem permissions and disk space)"
            );
            return false;
        }
    };
    match serde_json::from_str::<TosMarker>(&raw) {
        Ok(parsed) => parsed.version == CURRENT_TOS_VERSION,
        Err(e) => {
            tracing::warn!(
                path = %path.display(),
                error_kind = "gemini_tos_marker_parse_failed",
                error = %e,
                "Gemini ToS marker is malformed — treating as not acknowledged"
            );
            false
        }
    }
}

/// Atomically writes the marker at the current version with an
/// ISO-8601 timestamp from `SystemTime::now`. Idempotent.
pub fn acknowledge(base_dir: &Path) -> io::Result<TosMarker> {
    acknowledge_at(base_dir, current_timestamp())
}

/// Test helper that pins the timestamp.
pub(crate) fn acknowledge_at(base_dir: &Path, acknowledged_at: String) -> io::Result<TosMarker> {
    if !base_dir.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("base dir does not exist: {}", base_dir.display()),
        ));
    }

    let marker = TosMarker {
        acknowledged_at,
        version: CURRENT_TOS_VERSION,
    };
    let json =
        serde_json::to_string_pretty(&marker).map_err(|e| io::Error::other(e.to_string()))?;

    let target = tos_marker_path(base_dir);
    let tmp = unique_tmp_path(&target);

    if let Err(e) = std::fs::write(&tmp, json.as_bytes()) {
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    if let Err(e) = secure_file(&tmp) {
        let _ = std::fs::remove_file(&tmp);
        return Err(io::Error::other(e.to_string()));
    }
    if let Err(e) = atomic_replace(&tmp, &target) {
        let _ = std::fs::remove_file(&tmp);
        return Err(io::Error::other(e.to_string()));
    }

    Ok(marker)
}

fn current_timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format_utc_seconds(now)
}

fn format_utc_seconds(secs: u64) -> String {
    let days = (secs / 86_400) as i64;
    let sod = secs % 86_400;
    let (y, m, d) = civil_from_days(days);
    let hh = sod / 3600;
    let mm = (sod / 60) % 60;
    let ss = sod % 60;
    format!("{y:04}-{m:02}-{d:02}T{hh:02}:{mm:02}:{ss:02}Z")
}

fn civil_from_days(z: i64) -> (i32, u32, u32) {
    let z = z + 719_468;
    let era = (if z >= 0 { z } else { z - 146_096 }) / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    let y = if m <= 2 { y + 1 } else { y };
    (y as i32, m, d)
}

/// Probe whether `<home>/.gemini/oauth_creds.json` exists. The
/// desktop AddAccount modal uses this for INFORMATIONAL display:
/// when present, the user has previously authenticated gemini-cli
/// via Google OAuth (Code Assist), and binding a slot to AI Studio
/// API-key mode means csq's spawned gemini-cli will use the API key
/// and ignore the OAuth credentials. The note used to be framed as
/// a warning ("csq actively defends against OAuth fall-through" —
/// retracted in an internal journal entry); it is now a neutral data point so
/// users who have BOTH credential types know which one csq's slot
/// configuration will exercise.
///
/// Returns `Some(path)` when the file exists, `None` otherwise.
/// Uses [`std::fs::symlink_metadata`] so a dangling symlink — which
/// gemini-cli would still trip over — is reported as present.
///
/// Caller passes the home directory; csq-core doesn't depend on the
/// `dirs` crate, so the desktop crate (which already does) resolves
/// the path before invoking.
pub fn probe_oauth_residue(home_dir: &Path) -> Option<PathBuf> {
    let path = home_dir.join(".gemini").join("oauth_creds.json");
    if std::fs::symlink_metadata(&path).is_ok() {
        Some(path)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn is_acknowledged_returns_false_when_marker_missing() {
        let dir = TempDir::new().unwrap();
        assert!(!is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_then_is_acknowledged_returns_true() {
        let dir = TempDir::new().unwrap();
        acknowledge(dir.path()).unwrap();
        assert!(is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_writes_iso8601_timestamp_and_current_version() {
        let dir = TempDir::new().unwrap();
        let m = acknowledge_at(dir.path(), "2026-04-26T12:34:56Z".into()).unwrap();
        assert_eq!(m.version, CURRENT_TOS_VERSION);
        assert_eq!(m.acknowledged_at, "2026-04-26T12:34:56Z");

        let raw = std::fs::read_to_string(tos_marker_path(dir.path())).unwrap();
        assert!(raw.contains(&format!("\"version\": {}", CURRENT_TOS_VERSION)));
        assert!(raw.contains("2026-04-26T12:34:56Z"));
    }

    #[test]
    fn acknowledge_is_idempotent() {
        let dir = TempDir::new().unwrap();
        acknowledge_at(dir.path(), "2026-04-26T00:00:00Z".into()).unwrap();
        acknowledge_at(dir.path(), "2026-04-26T00:00:01Z".into()).unwrap();
        assert!(is_acknowledged(dir.path()));
        let raw = std::fs::read_to_string(tos_marker_path(dir.path())).unwrap();
        assert!(raw.contains("2026-04-26T00:00:01Z"));
    }

    #[test]
    fn wrong_version_is_not_acknowledged() {
        let dir = TempDir::new().unwrap();
        let path = tos_marker_path(dir.path());
        std::fs::write(
            &path,
            r#"{"acknowledged_at":"2026-01-01T00:00:00Z","version":99}"#,
        )
        .unwrap();
        assert!(
            !is_acknowledged(dir.path()),
            "a newer version in the file means the user has not seen the CURRENT disclosure"
        );
    }

    #[test]
    fn malformed_marker_is_not_acknowledged() {
        let dir = TempDir::new().unwrap();
        let path = tos_marker_path(dir.path());
        std::fs::write(&path, "not json").unwrap();
        assert!(!is_acknowledged(dir.path()));
    }

    #[test]
    fn acknowledge_rejects_nonexistent_base_dir() {
        let dir = TempDir::new().unwrap();
        let missing = dir.path().join("does-not-exist");
        let err = acknowledge(&missing).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::NotFound);
    }

    #[cfg(unix)]
    #[test]
    fn marker_file_is_mode_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        acknowledge(dir.path()).unwrap();
        let mode = std::fs::metadata(tos_marker_path(dir.path()))
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600, "ToS marker must be 0o600");
    }

    #[test]
    fn format_utc_seconds_round_numbers() {
        assert_eq!(format_utc_seconds(0), "1970-01-01T00:00:00Z");
        assert_eq!(format_utc_seconds(86_400), "1970-01-02T00:00:00Z");
        assert_eq!(format_utc_seconds(1_775_722_800), "2026-04-09T08:20:00Z");
    }

    #[test]
    fn probe_oauth_residue_returns_none_when_absent() {
        let dir = TempDir::new().unwrap();
        assert!(probe_oauth_residue(dir.path()).is_none());
    }

    #[test]
    fn probe_oauth_residue_returns_path_when_present() {
        let dir = TempDir::new().unwrap();
        let gemini = dir.path().join(".gemini");
        std::fs::create_dir_all(&gemini).unwrap();
        let creds = gemini.join("oauth_creds.json");
        std::fs::write(&creds, b"{}").unwrap();

        let found = probe_oauth_residue(dir.path()).expect("residue must be detected");
        assert_eq!(found, creds);
    }

    #[cfg(unix)]
    #[test]
    fn probe_oauth_residue_detects_dangling_symlink() {
        use std::os::unix::fs::symlink;
        let dir = TempDir::new().unwrap();
        let gemini = dir.path().join(".gemini");
        std::fs::create_dir_all(&gemini).unwrap();
        symlink(
            dir.path().join("nowhere.json"),
            gemini.join("oauth_creds.json"),
        )
        .unwrap();
        assert!(
            probe_oauth_residue(dir.path()).is_some(),
            "dangling symlink at the residue path is still 'present' — gemini-cli \
             would dereference it and we want the user warned"
        );
    }
}
