#!/usr/bin/env bash
set -euo pipefail

# Claude Squad installer — multi-account rotation for Claude Code
# macOS / Linux / WSL / Git Bash on Windows
# Install: curl -sSL https://raw.githubusercontent.com/terrene-foundation/claude-squad/main/install.sh | bash

REPO_URL="https://raw.githubusercontent.com/terrene-foundation/claude-squad/main"
ACCOUNTS_DIR="$HOME/.claude/accounts"
if [[ -d "$HOME/bin" ]] && echo "$PATH" | grep -q "$HOME/bin"; then
    BIN_DIR="$HOME/bin"
else
    BIN_DIR="$HOME/.local/bin"
fi

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }

# ─── Platform detection ─────────────────────────────────
detect_platform() {
    case "$(uname -s)" in
        Darwin) echo "macos" ;;
        Linux)
            if grep -qi microsoft /proc/version 2>/dev/null; then
                echo "wsl"
            else
                echo "linux"
            fi ;;
        MINGW*|MSYS*|CYGWIN*) echo "git-bash" ;;
        *) echo "unknown" ;;
    esac
}
PLATFORM=$(detect_platform)

# ─── Python detection ───────────────────────────────────
# Windows ships Python as `python` or `py -3`, not `python3`. Resolve once
# and use the result everywhere (including writing the resolved name into
# the deployed shell scripts so they don't have to detect on every render).
find_python() {
    for cmd in python3 python py; do
        if command -v "$cmd" &>/dev/null; then
            if "$cmd" --version 2>&1 | grep -q "Python 3"; then
                echo "$cmd"
                return
            fi
        fi
    done
    return 1
}

# ─── Package manager hint ───────────────────────────────
suggest_install() {
    local pkg="$1"
    case "$PLATFORM" in
        macos)
            command -v brew &>/dev/null && echo "brew install $pkg" || echo "install $pkg via Homebrew" ;;
        linux|wsl)
            if command -v apt &>/dev/null; then echo "sudo apt install $pkg"
            elif command -v dnf &>/dev/null; then echo "sudo dnf install $pkg"
            elif command -v pacman &>/dev/null; then echo "sudo pacman -S $pkg"
            elif command -v zypper &>/dev/null; then echo "sudo zypper install $pkg"
            else echo "install $pkg via your package manager"
            fi ;;
        git-bash)
            echo "install $pkg via Scoop, Chocolatey, or download from the project page" ;;
        *)
            echo "install $pkg via your package manager" ;;
    esac
}

echo -e "\n${BOLD}Claude Squad — Multi-Account Rotation for Claude Code${NC}\n"
echo -e "Platform: ${BOLD}${PLATFORM}${NC}\n"

# ─── Prerequisites ──────────────────────────────────────
command -v claude &>/dev/null || { err "Claude Code not found. Install: https://docs.anthropic.com/en/docs/claude-code"; exit 1; }

PYTHON=$(find_python) || { err "Python 3 not found. $(suggest_install python3)"; exit 1; }
ok "Python 3 found ($PYTHON)"

if ! command -v jq &>/dev/null; then
    warn "jq not found — statusline will not show quota. $(suggest_install jq)"
fi

mkdir -p "$ACCOUNTS_DIR/credentials" "$BIN_DIR"

# chmod is a no-op on Windows (NTFS profile dirs are user-private already)
if [[ "$PLATFORM" != "git-bash" ]]; then
    chmod 700 "$ACCOUNTS_DIR" "$ACCOUNTS_DIR/credentials"
fi

# ─── Install files ──────────────────────────────────────
if [[ -f "$(dirname "$0")/rotation-engine.py" ]]; then
    SRC="$(cd "$(dirname "$0")" && pwd)"
    cp "$SRC/rotation-engine.py" "$ACCOUNTS_DIR/rotation-engine.py"
    cp "$SRC/csq" "$BIN_DIR/csq"
    cp "$SRC/statusline-quota.sh" "$ACCOUNTS_DIR/statusline-quota.sh"
    cp "$SRC/3p-model-primer.md" "$ACCOUNTS_DIR/3p-model-primer.md"
    cp "$SRC/3p-model-primer-prepend.md" "$ACCOUNTS_DIR/3p-model-primer-prepend.md"
else
    curl -sfL "$REPO_URL/rotation-engine.py" -o "$ACCOUNTS_DIR/rotation-engine.py"
    curl -sfL "$REPO_URL/csq" -o "$BIN_DIR/csq"
    curl -sfL "$REPO_URL/statusline-quota.sh" -o "$ACCOUNTS_DIR/statusline-quota.sh"
    curl -sfL "$REPO_URL/3p-model-primer.md" -o "$ACCOUNTS_DIR/3p-model-primer.md"
    curl -sfL "$REPO_URL/3p-model-primer-prepend.md" -o "$ACCOUNTS_DIR/3p-model-primer-prepend.md"
fi

# auto-rotate-hook.sh: write a no-op so any pre-existing UserPromptSubmit
# hook entry in settings.json (or in per-config-dir snapshots) doesn't ENOENT.
# csq does not wire this hook on fresh installs. Old installs that had it
# wired will execute the no-op until the per-config snapshots get
# regenerated by `csq run`.
cat > "$ACCOUNTS_DIR/auto-rotate-hook.sh" << 'AUTOROTATEHOOK'
#!/usr/bin/env bash
# Auto-rotation hook — DISABLED (no-op).
# Auto-rotation caused random account switching on stale rate_limits data.
# Users manually swap with `! csq swap N` when they hit a rate limit.
exit 0
AUTOROTATEHOOK

# Migrate old installs:
#  - stale statusline-command.sh from pre-2.x installs deployed at the wrong location
#  - obsolete /rotate slash command
rm -f "$HOME/.claude/statusline-command.sh" 2>/dev/null || true
rm -f "$HOME/.claude/commands/rotate.md" 2>/dev/null || true

if [[ "$PLATFORM" != "git-bash" ]]; then
    chmod +x "$ACCOUNTS_DIR/rotation-engine.py" "$BIN_DIR/csq" \
             "$ACCOUNTS_DIR/statusline-quota.sh" \
             "$ACCOUNTS_DIR/auto-rotate-hook.sh"
fi
ok "Files installed"

# Remove old 'cc' binary if it exists (renamed to csq)
rm -f "$BIN_DIR/cc" 2>/dev/null

# ─── Config dirs ────────────────────────────────────────
for n in 1 2 3 4 5 6 7; do
    mkdir -p "$ACCOUNTS_DIR/config-$n"
done
ok "Config dirs created"

case "$PLATFORM" in
    macos) ok "Credential storage: macOS Keychain + file fallback" ;;
    linux|wsl) ok "Credential storage: file-only (no keychain on Linux)" ;;
    git-bash) ok "Credential storage: file-only (no keychain on Windows)" ;;
esac

# ─── Patch settings.json ────────────────────────────────
SETTINGS_FILE="$HOME/.claude/settings.json"
[[ -f "$SETTINGS_FILE" ]] || echo '{}' > "$SETTINGS_FILE"
CSQ_SETTINGS="$SETTINGS_FILE" "$PYTHON" -c "
import json, os
f = os.environ['CSQ_SETTINGS']
try:
    with open(f) as fh: s = json.load(fh)
except (FileNotFoundError, json.JSONDecodeError, ValueError): s = {}
changed = False

# Statusline — always force to canonical path. A previous install may have
# pointed at ~/.claude/statusline-command.sh; that's a stale location.
desired_sl_cmd = 'bash ~/.claude/accounts/statusline-quota.sh'
sl = s.get('statusLine', {})
if sl.get('command') != desired_sl_cmd:
    s['statusLine'] = {'type':'command','command':desired_sl_cmd}
    changed = True

# Remove the dead auto-rotate hook from settings.json if a previous install
# wired it up. csq is manual-only now — see journal/0010 for rationale.
hook_cmd_dead = 'bash ~/.claude/accounts/auto-rotate-hook.sh'
uph = s.get('hooks', {}).get('UserPromptSubmit', [])
new_uph = [e for e in uph if hook_cmd_dead not in str(e)]
if new_uph != uph:
    s.setdefault('hooks', {})['UserPromptSubmit'] = new_uph
    if not new_uph:
        del s['hooks']['UserPromptSubmit']
    changed = True

if changed:
    with open(f,'w') as fh: json.dump(s, fh, indent=2)
" 2>/dev/null
ok "Settings configured (statusline)"

if ! echo "$PATH" | grep -q "$BIN_DIR"; then
    warn "$BIN_DIR not in PATH. Add to your shell profile:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
fi

echo -e "\n${BOLD}Done.${NC} Now save your accounts:\n"
echo "  1. Start Claude:   claude"
echo "  2. Log in:          /login email@example.com"
echo "  3. Save it:         ! csq login 1"
echo "  4. Repeat for each account (slots 1-7)"
echo ""
echo "Daily use:"
echo "  csq run 1           Start CC on account 1 (isolated)"
echo "  csq run 3           Start CC on account 3 (separate terminal)"
echo "  csq status          Show all accounts + quota"
echo ""
echo "When rate limited (inside CC):"
echo "  ! csq swap N         Swap THIS terminal to account N (no restart, same conversation)"
echo "  ! csq suggest        Show which account has the most quota"
echo ""
