//! Shared `ALL`-derivation macro for csq-core's fieldless enums.
//!
//! Crate-internal only (`mod all_enum;` in `lib.rs`, no `#[macro_export]`) —
//! deliberately NOT shared across the `csq-core` / `csq-sdk` crate boundary.
//! `csq-sdk::capabilities::LoginFlow` carries its own copy of this same
//! macro shape: sharing it here would mean `#[macro_export]`-ing a generic
//! codegen helper from `csq-sdk`, whose stated charter is the wire-contract
//! DTO surface, into that crate's PERMANENT public API (crates.io + the
//! community fork) — a semver commitment with no relationship to the
//! wire contract, for the sake of one extra consumer. A brand-new leaf
//! crate to host it was also considered and rejected: workspace-membership,
//! `Cargo.toml`, README/license, and `check-edition-boundary.py` overhead is
//! not worth it for a ~20-line macro with all its OTHER consumers already
//! living in this one crate. `csq-core` already depends on `csq-sdk`
//! (the allowed PROPRIETARY→OPEN direction, `edition-boundary.md`), so
//! nothing here creates a new cross-crate edge either way.
//!
//! # The class this macro exists to close
//!
//! Every one of csq-core's `Foo::ALL: &'static [Foo]` constants existed to
//! answer one question: "does every variant of `Foo` appear in this list?"
//! Each was hand-maintained, and each shipped a regression test NAMED for
//! that exact completeness property — while unable to check it. Two
//! shapes of the same failure recurred independently:
//!
//! - **The circular-match shape** (`Surface::ALL`, fixed in the commit that
//!   added this module): the "exhaustive" match in the completeness test
//!   ran over values drawn FROM `ALL`'s own contents, not over the type's
//!   full variant space — so a variant `ALL` never included was a value
//!   that loop could never be asked to cover, and the match's real,
//!   compiler-enforced exhaustiveness (it DOES fail to compile on a new
//!   variant) only forced a new match arm, never a new `ALL` entry.
//! - **The hardcoded-length-pin shape** (`SurfaceCli::ALL`, `EventKind::ALL`,
//!   `Oq1Category::ALL`, `Oq1Tier::ALL`): a `assert_eq!(Foo::ALL.len(), N)`
//!   (or a `const`-eval equivalent) pins a literal count. A variant added
//!   with its required arm elsewhere (some OTHER exhaustive match forces
//!   that) but never pushed into `ALL`, with the literal `N` left
//!   unbumped, satisfies the pin: `ALL.len()` and `N` are both unchanged,
//!   both still equal each other, and the assertion — which reads as
//!   `ALL is complete` — never fires. A `const`-eval assertion is the MORE
//!   dangerous variant of this shape, not the safer one: it looks like a
//!   compile-time guarantee to a reviewer skimming for rigor, and it is
//!   just as blind as its runtime sibling — it still measures `ALL`
//!   against `ALL`'s own recorded length, never against the enum's actual
//!   variant count.
//!
//! Both shapes have the same root cause: nothing forces the two SITES —
//! the enum definition and the `ALL` literal — to move together. This
//! macro removes the second site. `Foo` and `Foo::ALL` are generated from
//! ONE list of variant identifiers in ONE macro expansion, so there is no
//! longer an edit that adds a variant to the enum without that same edit
//! adding it to `ALL` — they are the same token stream, not two lists a
//! human keeps in sync by discipline.
//!
//! # Shape: always `&'static [Self]`, never `[Self; N]`
//!
//! `EventKind` and `Oq1Category`/`Oq1Tier` previously declared `ALL` as a
//! fixed-size array (`[Self; 26]`, `[Self; 9]`, `[Self; 2]`). This macro
//! emits a slice uniformly instead. Array-length inference in a `const`
//! item's type position is not worth the macro complexity a branching
//! slice-vs-array shape would add, and every consumer found by grep across
//! the crate uses `.iter()`, `.len()`, or `for x in Foo::ALL` — all
//! identical on either shape. The one call site that assumed
//! array-by-value iteration (`audit::authority::op_class::all_event_kinds_are_classified`,
//! which took `&kind` on a value already owned via array `IntoIterator`)
//! is adjusted to `kind` (already a `&EventKind` under slice iteration) in
//! the same commit that migrates `EventKind`.
macro_rules! declare_all_enum {
    (
        $(#[$enum_meta:meta])*
        $vis:vis enum $name:ident {
            $(
                $(#[$variant_meta:meta])*
                $variant:ident
            ),+ $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        $vis enum $name {
            $(
                $(#[$variant_meta])*
                $variant
            ),+
        }

        impl $name {
            /// Every variant, in declaration order. Generated by
            /// [`declare_all_enum!`](crate::all_enum::declare_all_enum) from
            /// the SAME identifier list that defines this enum — there is
            /// only one place a variant name is written, so `ALL`
            /// structurally cannot omit a variant the enum has. See the
            /// macro's own doc (`csq-core/src/all_enum.rs`) for the defect
            /// class this replaces.
            pub const ALL: &'static [$name] = &[$($name::$variant),+];
        }
    };
}

pub(crate) use declare_all_enum;
